### ISSUE TITLE
Set up black formatter pre-commit for the repo. 

### ISSUE THREAD

**Issue by jbloomAus** [jbloomAus/DecisionTransformerInterpretability#10]
Follow this tutorial: https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/

**Comment by wtesqie1** [comment]
I'll work on this.

**Comment by wtesqie1** [comment]
Did you also want to set-up flake8?

**Comment by jbloomAus** [comment]
I think flake8 is set up already in the github actions so having it in
pre-commit is probably also a good idea!

**Comment by JayBaileyCS** [comment]
Can this be closed at this point?

**Comment by jbloomAus** [comment]
yes, can make a seperate card for gh action https://black.readthedocs.io/en/stable/integrations/github_actions.html
