### ISSUE TITLE
Remove git lfs

### ISSUE THREAD

**Issue by DalasNoin** [jbloomAus/DecisionTransformerInterpretability#2]
While cloning or otherwise working with the repo I saw errors like these ones:
```
error: external filter 'git-lfs filter-process' failed. I assume it is related to this file fatal: trajectories/MiniGrid-Dynamic-Obstacles-8x8-v0bd60729d-dc0b-4294-9110-8d5f672aa82c.pkl:

Error downloading object: trajectories/MiniGrid-Dynamic-Obstacles-8x8-v0bd60729d-dc0b-4294-9110-8d5f672aa82c.pkl (8c06bc4): Smudge error: Error downloading trajectories/MiniGrid-Dynamic-Obstacles-8x8-v0bd60729d-dc0b-4294-9110-8d5f672aa82c.pkl
```

This error message is seemingly related to Git Large File Storage (LFS). The error message indicates that the git-lfs filter-process command failed. This error can occur if Git LFS is not installed or if the Git LFS filters are not configured correctly.

This solution appears to work for me:

Check if git-lfs is installed and install it if it is not.

```
git lfs install --skip-smudge
git clone <your-repo-url>
git lfs pull
git lfs install --force
```

The --skip-smudge option tells Git LFS to skip the smudge filter, which is responsible for downloading the large files. The git clone command clones the repository. The git lfs pull command downloads the large files. Finally, the --force option reinstates the smudge filter.

Maybe it would be helpful to add something on git lfs in the Readme or somewhere else.

**Comment by jbloomAus** [comment]
Thanks for raising this. I'll take a look after my current sprint :)

**Comment by DalasNoin** [comment]
```batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.```

**Comment by jbloomAus** [comment]
Thanks, will sort out today.

**Comment by jbloomAus** [comment]
Renaming, will remove git lfs. it's too annoying.

**Comment by jbloomAus** [comment]
this should be sorted.
